In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

pd.set_option('display.max_columns',50)
pd.options.display.max_rows

60

In [47]:
a = pd.read_csv('listings.csv')
a.head(1)

,id,listing_url,scrape_id,last_scraped,name,summary,space,description,experiences_offered,neighborhood_overview,notes,transit,access,interaction,house_rules,thumbnail_url,medium_url,picture_url,xl_picture_url,host_id,host_url,host_name,host_since,host_location,host_about,...,calendar_last_scraped,number_of_reviews,number_of_reviews_ltm,first_review,last_review,review_scores_rating,review_scores_accuracy,review_scores_cleanliness,review_scores_checkin,review_scores_communication,review_scores_location,review_scores_value,requires_license,license,jurisdiction_names,instant_bookable,is_business_travel_ready,cancellation_policy,require_guest_profile_picture,require_guest_phone_verification,calculated_host_listings_count,calculated_host_listings_count_entire_homes,calculated_host_listings_count_private_rooms,calculated_host_listings_count_shared_rooms,reviews_per_month
0,109,https://www.airbnb.com/rooms/109,20190708161040,2019-07-09,Amazing bright elegant condo park front *UPGRA...,"*** Unit upgraded with new bamboo flooring, br...","*** Unit upgraded with new bamboo flooring, br...","*** Unit upgraded with new bamboo flooring, br...",none,NaN,NaN,NaN,NaN,NaN,Camelot NEW RESIDENTS’ GENERAL INFORMATION F...,NaN,NaN,https://a0.muscache.com/im/pictures/4321499/1d...,NaN,521,https://www.airbnb.com/users/show/521,Paolo,2008-06-27,"San Francisco, California, United States",Search for me on the Internet with the keyword...,...,2019-07-09,2,0,2011-08-15,2016-05-15,80.0,10.0,10.0,6.0,8.0,10.0,8.0,f,NaN,"{""Culver City"","" CA""}",f,f,strict_14_with_grace_period,t,f,1,1,0,0,0.02

In [17]:
lst = ['listing_url','scrape_id','last_scraped','summary',\
       'space','description','experiences_offered','neighborhood_overview','interaction','access','house_rules',\
       'notes','thumbnail_url','medium_url','picture_url','host_url',\
      'host_about','host_response_rate','host_acceptance_rate','host_thumbnail_url','host_picture_url',\
       'host_listings_count','host_has_profile_pic','host_verifications','host_neighbourhood',\
       'neighbourhood_cleansed','neighbourhood_group_cleansed','market','smart_location','country_code',\
      'country','is_location_exact','square_feet','weekly_price','monthly_price','minimum_minimum_nights',\
      'minimum_minimum_nights','maximum_minimum_nights','minimum_maximum_nights','maximum_maximum_nights',\
      'minimum_nights_avg_ntm','maximum_nights_avg_ntm','calendar_updated','has_availability','calendar_last_scraped',\
      'availability_30','availability_60','availability_90','availability_365','number_of_reviews_ltm',\
       'requires_license','license','jurisdiction_names','is_business_travel_ready','require_guest_profile_picture',\
      'require_guest_phone_verification','calculated_host_listings_count','calculated_host_listings_count_entire_homes',\
      'calculated_host_listings_count_private_rooms','calculated_host_listings_count_shared_rooms','xl_picture_url',\
      ]
a.drop(columns=lst,inplace=True)

In [18]:
a.shape

(44620, 46)

In [19]:
df = a.copy()

In [20]:
df['colid'] = df.index

In [21]:
df.head(2)
df.drop('id',axis=1,inplace=True)

In [22]:
#df1 = df[['id','colid']].copy()
#.reset_index(drop=True,inplace=True)
df.rename(columns={'colid':'id'},inplace=True)

In [23]:
df.id +=1

In [24]:
df.set_index('id',inplace=True)
df.head(1)

,name,transit,host_id,host_name,host_since,host_location,host_response_time,host_is_superhost,host_total_listings_count,host_identity_verified,street,neighbourhood,city,state,zipcode,latitude,longitude,property_type,room_type,accommodates,bathrooms,bedrooms,beds,bed_type,amenities,price,security_deposit,cleaning_fee,guests_included,extra_people,minimum_nights,maximum_nights,number_of_reviews,first_review,last_review,review_scores_rating,review_scores_accuracy,review_scores_cleanliness,review_scores_checkin,review_scores_communication,review_scores_location,review_scores_value,instant_bookable,cancellation_policy,reviews_per_month
id,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,
1,Amazing bright elegant condo park front *UPGRA...,NaN,521,Paolo,2008-06-27,"San Francisco, California, United States",NaN,f,1.0,t,"Culver City, CA, United States",Culver City,Culver City,CA,90230,33.98209,-118.38494,Condominium,Entire home/apt,6,2.0,2.0,3.0,Real Bed,"{TV,""Cable TV"",Internet,Wifi,""Air conditioning...",$122.00,$500.00,$240.00,3,$25.00,30,730,2,2011-08-15,2016-05-15,80.0,10.0,10.0,6.0,8.0,10.0,8.0,f,strict_14_with_grace_period,0.02

In [37]:
df.shape

(44620, 45)

In [25]:
df1 = df.copy()

## Cleaning the city column & state column

In [26]:
#df.rename(index={'Afghanistan':'Afghanistan_renamed'})
df1.state.loc[df1.state=='California'] = 'CA'
df1.state.unique()
df1.state = df1['state'].str.upper()

In [27]:
df1.state.value_counts()

CA    44611
NY        2
加州        2
IL        1
加洲        1
FL        1
Name: state, dtype: int64

In [28]:
#df[~(df.state=='CA')].drop
#df1.drop(df1[(df1['Year'].values==1970)].index,axis=0,inplace=True)
#a = df.state[~(df.state=='CA')]
df1.drop(df1[~(df1.state.values=='CA')].index,axis=0,inplace=True)

In [29]:
#df.groupby('host_location')['city'].unique()
df1.city = df1.city.str.lower()

#df1.city.loc[df1.city=='n hollywood'] = 'north hollywood'
#df1.city.loc[df1.city=='granada hills, (los angeles)'] = 'granada hills'

df1.city.unique()
#df.loc[df.city=='venice'].groupby('neighbourhood')['street'].value_counts()
df1.city.dropna(inplace=True)
## Contains checks for anything which contains venice and not just venice 
df1.city[df1.city.str.contains('venice')==True].value_counts()
df1.city.loc[df1.city.str.contains('venice')] = 'los angeles'
df1.city.unique()

array(['culver city', 'burbank', 'los angeles', 'santa monica',
       'bellflower', 'woodland hills', 'beverly hills', 'long beach',
       'redondo beach', 'torrance', 'n hollywood', 'studio city',
       'glendale', 'malibu', 'san fernando valley', 'lynwood',
       'hollywood', 'granada hills, (los angeles)', 'west hollywood',
       'encino', 'north hills', 'carson', 'north hollywood', 'altadena',
       'calabasas', 'hollywood hills', 'agoura hills-malibu',
       'manhattan beach', 'sherman oaks', 'topanga',
       'rancho palos verdes', 'san gabriel', 'marina del rey', 'lakewood',
       'topanga canyon', 'sierra madre', 'pasadena', 'agua dulce',
       'hermosa beach', 'compton', 'pacific palisades', 'el segundo',
       'los angeles county', 'inglewood', 'covina', 'rowland heights',
       'south pasadena', 'la cañada flintridge', 'montrose', 'walnut',
       'playa del rey', 'whittier', 'littlerock', 'alhambra',
       'baldwin park', 'agoura hills', 'monrovia', 'montebello',
       'valley village', 'rolling hills estates', 'winnetka', 'tarzana',
       'lomita', 'sherman oaks, los angeles', 'san fernando', 'reseda',
       'valley glen', 'san pedro', 'burbank, los angeles', 'palmdale',
       'north hollywood ', 'san dimas', ' los angeles', 'hawthorne',
       'hollywood, hollywood hills, los angeles', 'northridge',
       'canoga park', 'woodland hls', 'west covina', 'santa clarita',
       'monterey hill. los angeles', 'san pedro los angeles ',
       'toluca lake', 'playa vista', 'arcadia', 'la habra heights',
       'rowland heights / hacienda heights', 'malibu ',
       'pasadena, los angeles', 'san marino', 'silver lake', 'claremont',
       'valencia', 'west los angeles', 'harbor city', 'gardena',
       'lawndale', 'west hills', 'lancaster', 'downey', 'van nuys',
       'east los angeles', 'pico rivera', 'avalon', 'monterey park',
       'hollywood  ', 'no hollywood', 'el monte',
       'north hollywood (toluca lake)', 'la mirada', 'diamond bar',
       'silver lake, los angeles', 'hacienda heights', 'bell',
       'val verde', 'azusa', 'echo park', 'woodland hills, los angeles',
       'huntington park', 'glendora', 'palos verdes estates',
       'лос-анджелес', 'temple city', 'los feliz, los angeles',
       'la crescenta-montrose', 'la', 'cerritos',
       'pacific palisades, los angeles', 'windsor hills', 'norwalk',
       'bel air', 'stevenson ranch', 'sherman oaks, ', 'granada hills',
       'toluca lake (los angeles area)', 'lake balboa', 'studio city ',
       'castaic', 'los angeles, noho art district', 'los angeles ',
       'signal hill', 'duarte', 'westchester', 'beverly grove',
       'west hollywood ', 'pomona', 'hollywood ',
       'san pedro, los angeles', 'artesia', 'malibu canyon/monte nido',
       'sherwood forest', 'oak park', 'west hollywood hills', 'la verne',
       '蒙特利帕克', 'south gate', 'hollywood hills, los angeles', 'upland',
       'north hollywood los angeles studio city', 'rowland helghts',
       'woodland hills (los angeles)', 'wrightwood', 'valencia ',
       'rosemead', 'lake los angeles', 'los angeles / beverly hills',
       'woodland hills ', 'sherman oaks ', 'chatsworth',
       'echo park, los angeles', 'san pedro los angeles',
       'south el monte', 'del aire', 'la puente', 'mar vista',
       'bell gardens', 'paramount', 'lake hughes', ' encino',
       'view park-windsor hills', 'los angeles (montecito heights)',
       'encino, los angeles', 'pasadena ', '因達斯特里', 'los angeles ca',
       '艾尔蒙地', 'sun valley', 'los angeles    ', 'valyermo',
       'rowland height ', 'beverly hills ( post office) zip code',
       'los angeles, hollywood hills', 'hollywood heights', 'lennox', 'p',
       'los angeles, studio city, tujunga village', 'playa del rey ',
       'thousand oaks', 'reseda , los angeles', 'canoga park ', '沃尔纳特',
       'northridge ', 'redo do beach', 'westlake village',
       'rowland heights ', 'west hills,los angeles', 'van nuys ',
       'west hills ,los angeles', 'acton', 'lost angeles',
       'palos verdes peninsula', 'van nuys, los angeles',
       'marina del rey ', 'quartz hill', 'san gabriel/rosemead',
       'monterey park ', 'maywood', 'select cities', 'malibu beach',
       'view park', 'westminster', 'downtown los angeles', 'torrance ',
       'canyon country ', 'pacific palisades ', 'windsor hills ',
       'glendale, california, us', 'phillips ranch ', 'mount baldy',
       'long beach ', '哈仙达岗', '罗兰高地', 'arcadia ',
       'los angeles/ hollywood ', 'phillips ranch', 'city of industry',
       'playa vista ', 'chatsworth ', 'tarzana ', 'granada hills ',
       'sylmar', 'playa', 'green valley', 'reseda ', 'el camino village',
       'bradbury', 'covina hills', 'beverly hills ', 'rowland hghts',
       'llano', 'valley village ', 'universal city', 'cudahy',
       'san pedro ', 'west carson', 'encino ', 'sunland ',
       'rolling hills', 'la habra', 'simi valley', 'tujunga',
       'el segundo, california, us', 'lincoln heights ',
       'beverly hills/ los angeles', 'tempcity',
       'los angeles/burbank/toluca lake', 'bixby knolls ',
       'historic highland park zoning montecito heights', 'gardena ',
       '罗兰岗', 'los angeles (elysian valley)', 'rowland heigh',
       'mission hills ', 'wilmington', 'woodland hills/los angeles',
       'commerce', 'south bay', 'westwood ', 'wilmington ', '天普市',
       'silverlake, los angeles ', 'el monte ', 'encino ca', 'pacoima',
       'west covina ', 'leona valley', 'south san gabriel',
       'westchester ', 'rosemead ', 'east edna pi.covina',
       'los angeles ca ', 'montebello ', 'los angeles, woodland hills ',
       'toluca ', 'oakland', 'los angeles, tarzana ', 'los angeles city',
       'santa monica ', 'west puente valley', 'century city',
       'canola park', 'winnetka ', 'mission hills', 'pacoima ', '洛杉矶',
       'elizabeth lake', ' hollywood', 'latuna canyon', 'palm springs',
       ' los angeles ', 'avocado heights', 'temple city ', 'study city',
       'glendora ', 'porter ranch ', 'roesmead', 'san gabriel ',
       'koreatown los angeles', 'arleta', 'west hills ',
       'los angeles / hollywood ', 'sun valley ', 'hacienda heights ',
       'los angeles / valley village / north hollywood ',
       'los angeles/la crescenta', 'seal beach', 'west la', 'industry',
       'los angels ', 'east san gabriel', 'north hollywood, los angeles'],
      dtype=object)

In [32]:
df1.groupby('city')['neighbourhood'].value_counts()

city                          neighbourhood
                              Monterey Park                    2
                              West Covina                      2
                              El Monte                         1
                              Rosemead                         1
                              Temple City                      1
                                                              ..
woodland hills                Woodland Hills/Warner Center    12
woodland hills (los angeles)  Woodland Hills/Warner Center     1
woodland hills, los angeles   Woodland Hills/Warner Center     1
woodland hills/los angeles    Woodland Hills/Warner Center     1
woodland hls                  Woodland Hills/Warner Center     1
Name: neighbourhood, Length: 627, dtype: int64

In [33]:
df1['city'] = df1['city'].str.replace(r'[^\x00-\x7F]+', '')
df1.city.dropna(inplace=True)
df1.city.value_counts()

los angeles                        28339
long beach                          1612
santa monica                        1059
west hollywood                       973
beverly hills                        767
                                   ...
canoga park                            1
los angeles/burbank/toluca lake        1
rowland heigh                          1
los angels                             1
covina hills                           1
Name: city, Length: 323, dtype: int64

In [34]:
df1.city[df1.city.str.contains('los angeles')==True].value_counts()
df1.groupby
#df.city.loc[df.city.str.contains('los angeles')] = 'los angeles'
#df.city.unique()

<bound method NDFrame.groupby of                                                     name  \
id
1      Amazing bright elegant condo park front *UPGRA...
2                      Family perfect;Pool;Near Studios!
3      Fireplace Mirrored Mini Suit (Website hidden b...
4                                  Zen Life at the Beach
5      *Upscale Professional Home with Beautiful Studio*
...                                                  ...
44616  Amazing private room and (Website hidden by Ai...
44617     Beach area! Furnished bedroom private bathroom
44618  Spanish Style Dream Vacation Mansion in Hearto...
44619     Beautiful Apartment The Heart Of Beverly Hills
44620    Private Room near LAX with Rentable Car & Pool!

                                                 transit    host_id  \
id
1                                                    NaN        521
2      Short drive to subway and elevated trains runn...        767
3      There are many buses; bus stops going in every...       3008
4                                                    NaN       3041
5      Public transportation is a 3 minutes walk to t...       3207
...                                                  ...        ...
44616  My place is right by the park. And 3 min from ...  162830951
44617                                                NaN  131942605
44618                                                NaN  102908962
44619                             Walking  Bus Uber/Lyft  190141879
44620                                                NaN   22623490

            host_name  host_since                             host_location  \
id
1               Paolo  2008-06-27  San Francisco, California, United States
2             Melissa  2008-07-11        Burbank, California, United States
3               Chas.  2008-09-16    Los Angeles, California, United States
4      Yoga Priestess  2008-09-17   Santa Monica, California, United States
5           Bernadine  2008-09-25     Long Beach, California, United States
...               ...         ...                                       ...
44616        Siuzanna  2017-12-15    Los Angeles, California, United States
44617         Felicia  2017-05-25  Hermosa Beach, California, United States
44618           Chaim  2016-11-07    Los Angeles, California, United States
44619            Shay  2018-05-17  Beverly Hills, California, United States
44620          Girvan  2014-10-16    Los Angeles, California, United States

      host_response_time host_is_superhost  host_total_listings_count  \
id
1                    NaN                 f                        1.0
2           within a day                 f                        1.0
3         within an hour                 t                        2.0
4         within an hour                 t                        2.0
5                    NaN                 f                        1.0
...                  ...               ...                        ...
44616                NaN                 f                        1.0
44617     within an hour                 f                        7.0
44618     within an hour                 t                        6.0
44619                NaN                 f                        1.0
44620     within an hour                 t                        2.0

      host_identity_verified                            street  \
id
1                          t    Culver City, CA, United States
2                          t        Burbank, CA, United States
3                          t    Los Angeles, CA, United States
4                          t   Santa Monica, CA, United States
5                          t     Bellflower, CA, United States
...                      ...                               ...
44616                      f    Los Angeles, CA, United States
44617                      t    Los Angeles, CA, United States
44618                      f    Los Angeles, CA, United States
44619                      f  Beverly Hills, CA, United States
44620                      t      Inglewood, CA, United States

                   neighbourhood           city state zipcode  latitude  \
id
1                    Culver City    culver city    CA   90230  33.98209
2                        Burbank        burbank    CA   91505  34.16562
3                      Hollywood    los angeles    CA   90046  34.09768
4                   Santa Monica   santa monica    CA   90405  34.00475
5                     Bellflower     bellflower    CA   90706  33.87619
...                          ...            ...   ...     ...       ...
44616                   Westlake    los angeles    CA   90057  34.06128
44617  Westchester/Playa Del Rey    los angeles    CA   90293  33.95685
44618               Mid-Wilshire    los angeles    CA   90036  34.06680
44619              Beverly Hills  beverly hills    CA   90212  34.06459
44620                  Inglewood      inglewood    CA   90302  33.97381

       longitude property_type        room_type  accommodates  bathrooms  \
id
1     -118.38494   Condominium  Entire home/apt             6        2.0
2     -118.33458         House  Entire home/apt             6        1.0
3     -118.34602     Apartment     Private room             1        1.5
4     -118.48127     Apartment     Private room             1        1.0
5     -118.11397     Apartment  Entire home/apt             2        1.0
...          ...           ...              ...           ...        ...
44616 -118.27461     Apartment     Private room             2        1.0
44617 -118.43640     Apartment     Private room             1        1.0
44618 -118.35308         House  Entire home/apt            14        3.5
44619 -118.39732     Apartment     Private room             1        1.0
44620 -118.36640   Condominium     Private room             2        1.5

       bedrooms  beds       bed_type  \
id
1           2.0   3.0       Real Bed
2           3.0   3.0       Real Bed
3           1.0   1.0       Real Bed
4           1.0   1.0  Pull-out Sofa
5           1.0   1.0       Real Bed
...         ...   ...            ...
44616       1.0   1.0       Real Bed
44617       2.0   1.0       Real Bed
44618       5.0   9.0       Real Bed
44619       1.0   1.0       Real Bed
44620       1.0   1.0       Real Bed

                                               amenities    price  \
id
1      {TV,"Cable TV",Internet,Wifi,"Air conditioning...  $122.00
2      {TV,"Cable TV",Internet,Wifi,"Air conditioning...  $168.00
3      {Internet,Wifi,"Air conditioning","Wheelchair ...   $79.00
4      {Internet,Wifi,Kitchen,Heating,Washer,Dryer,"S...  $140.00
5      {TV,"Cable TV",Internet,Wifi,"Air conditioning...   $80.00
...                                                  ...      ...
44616  {TV,Wifi,"Air conditioning",Pool,Kitchen,"Free...   $55.00
44617  {Wifi,Kitchen,"Free parking on premises",Washe...   $59.00
44618  {TV,"Cable TV",Wifi,"Air conditioning",Kitchen...  $678.00
44619  {Wifi,"Air conditioning",Kitchen,Breakfast,Hea...   $99.00
44620  {TV,Wifi,Pool,Kitchen,"Free street parking",He...   $78.00

      security_deposit cleaning_fee  guests_included extra_people  \
id
1              $500.00      $240.00                3       $25.00
2                $0.00      $100.00                6        $0.00
3              $480.00       $89.00                1        $0.00
4                  NaN      $100.00                1        $0.00
5              $100.00       $75.00                1       $25.00
...                ...          ...              ...          ...
44616          $100.00       $30.00                1        $0.00
44617              NaN          NaN                1        $0.00
44618          $500.00      $225.00                1       $45.00
44619              NaN          NaN                1        $0.00
44620            $0.00        $0.00                1        $5.00

       minimum_nights  maximum_nights  number_of_reviews first_review  \
id
1                  30             730                  2   2011-08-15
2                   2              14                  6   2016-06-14
3                  28             366                 20   2014-06-09
4                   1             180                 18   2011-06-06
5                   2             730                  0          NaN
...               ...             ...                ...          ...
44616               2            1125                  0          NaN
44617              15            1125                  0          NaN
44618               2              30                  0          NaN
44619               7            1125                  0          NaN
44620               1               5                  0          NaN

      last_review  review_scores_rating  review_scores_accuracy  \
id
1      2016-05-15                  80.0                    10.0
2      2018-10-21                  93.0                    10.0
3      2019-05-20                  98.0                    10.0
4      2018-11-15                  96.0                     9.0
5             NaN                   NaN                     NaN
...           ...                   ...                     ...
44616         NaN                   NaN                     NaN
44617         NaN                   NaN                     NaN
44618         NaN                   NaN                     NaN
44619         NaN                   NaN                     NaN
44620         NaN                   NaN                     NaN

       review_scores_cleanliness  review_scores_checkin  \
id
1                           10.0                    6.0
2                           10.0                   10.0
3                           10.0                   10.0
4                            9.0                   10.0
5                            NaN                    NaN
...                          ...                    ...
44616                        NaN                    NaN
44617                        NaN                    NaN
44618                        NaN                    NaN
44619                        NaN                    NaN
44620                        NaN                    NaN

       review_scores_communication  review_scores_location  \
id
1                              8.0                    10.0
2                             10.0                    10.0
3                             10.0                    10.0
4                             10.0                    10.0
5                              NaN                     NaN
...                            ...                     ...
44616                          NaN                     NaN
44617                          NaN                     NaN
44618                          NaN                     NaN
44619                          NaN                     NaN
44620                          NaN                     NaN

       review_scores_value instant_bookable          cancellation_policy  \
id
1                      8.0                f  strict_14_with_grace_period
2                      9.0                t                     flexible
3                     10.0                t  strict_14_with_grace_period
4                      9.0                f  strict_14_with_grace_period
5                      NaN                f  strict_14_with_grace_period
...                    ...              ...                          ...
44616                  NaN                t                     moderate
44617                  NaN                t  strict_14_with_grace_period
44618                  NaN                f                     moderate
44619                  NaN                t                     flexible
44620                  NaN                t                     flexible

       reviews_per_month
id
1                   0.02
2                   0.16
3                   0.32
4                   0.18
5                    NaN
...                  ...
44616                NaN
44617                NaN
44618                NaN
44619                NaN
44620                NaN

[44611 rows x 45 columns]>

In [35]:
df1.shape

(44611, 45)

In [36]:
 df1.head()

,name,transit,host_id,host_name,host_since,host_location,host_response_time,host_is_superhost,host_total_listings_count,host_identity_verified,street,neighbourhood,city,state,zipcode,latitude,longitude,property_type,room_type,accommodates,bathrooms,bedrooms,beds,bed_type,amenities,price,security_deposit,cleaning_fee,guests_included,extra_people,minimum_nights,maximum_nights,number_of_reviews,first_review,last_review,review_scores_rating,review_scores_accuracy,review_scores_cleanliness,review_scores_checkin,review_scores_communication,review_scores_location,review_scores_value,instant_bookable,cancellation_policy,reviews_per_month
id,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,
1,Amazing bright elegant condo park front *UPGRA...,NaN,521,Paolo,2008-06-27,"San Francisco, California, United States",NaN,f,1.0,t,"Culver City, CA, United States",Culver City,culver city,CA,90230,33.98209,-118.38494,Condominium,Entire home/apt,6,2.0,2.0,3.0,Real Bed,"{TV,""Cable TV"",Internet,Wifi,""Air conditioning...",$122.00,$500.00,$240.00,3,$25.00,30,730,2,2011-08-15,2016-05-15,80.0,10.0,10.0,6.0,8.0,10.0,8.0,f,strict_14_with_grace_period,0.02
2,Family perfect;Pool;Near Studios!,Short drive to subway and elevated trains runn...,767,Melissa,2008-07-11,"Burbank, California, United States",within a day,f,1.0,t,"Burbank, CA, United States",Burbank,burbank,CA,91505,34.16562,-118.33458,House,Entire home/apt,6,1.0,3.0,3.0,Real Bed,"{TV,""Cable TV"",Internet,Wifi,""Air conditioning...",$168.00,$0.00,$100.00,6,$0.00,2,14,6,2016-06-14,2018-10-21,93.0,10.0,10.0,10.0,10.0,10.0,9.0,t,flexible,0.16
3,Fireplace Mirrored Mini Suit (Website hidden b...,There are many buses; bus stops going in every...,3008,Chas.,2008-09-16,"Los Angeles, California, United States",within an hour,t,2.0,t,"Los Angeles, CA, United States",Hollywood,los angeles,CA,90046,34.09768,-118.34602,Apartment,Private room,1,1.5,1.0,1.0,Real Bed,"{Internet,Wifi,""Air conditioning"",""Wheelchair ...",$79.00,$480.00,$89.00,1,$0.00,28,366,20,2014-06-09,2019-05-20,98.0,10.0,10.0,10.0,10.0,10.0,10.0,t,strict_14_with_grace_period,0.32
4,Zen Life at the Beach,NaN,3041,Yoga Priestess,2008-09-17,"Santa Monica, California, United States",within an hour,t,2.0,t,"Santa Monica, CA, United States",Santa Monica,santa monica,CA,90405,34.00475,-118.48127,Apartment,Private room,1,1.0,1.0,1.0,Pull-out Sofa,"{Internet,Wifi,Kitchen,Heating,Washer,Dryer,""S...",$140.00,NaN,$100.00,1,$0.00,1,180,18,2011-06-06,2018-11-15,96.0,9.0,9.0,10.0,10.0,10.0,9.0,f,strict_14_with_grace_period,0.18
5,*Upscale Professional Home with Beautiful Studio*,Public transportation is a 3 minutes walk to t...,3207,Bernadine,2008-09-25,"Long Beach, California, United States",NaN,f,1.0,t,"Bellflower, CA, United States",Bellflower,bellflower,CA,90706,33.87619,-118.11397,Apartment,Entire home/apt,2,1.0,1.0,1.0,Real Bed,"{TV,""Cable TV"",Internet,Wifi,""Air conditioning...",$80.00,$100.00,$75.00,1,$25.00,2,730,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,f,strict_14_with_grace_period,NaN

In [45]:
df1[df1.city=='los angeles'].value_counts()

C:\ProgramData\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: UserWarning: Boolean Series key will be reindexed to match DataFrame index.
  """Entry point for launching an IPython kernel.

IndexingError: Unalignable boolean Series provided as indexer (index of the boolean Series and of the indexed object do not match).